if(CMAKE_HOST_UNIX)
  string(ASCII 27 Esc)
  set(COLOR_RESET  "${Esc}[m")
  set(COLOR_BOLD   "${Esc}[1m")
  set(RED          "${Esc}[31m")
  set(GREEN        "${Esc}[32m")
  set(YELLOW       "${Esc}[33m")
  set(BLUE         "${Esc}[34m")
  set(MAGENTA      "${Esc}[35m")
  set(CYAN         "${Esc}[36m")
  set(WHITE        "${Esc}[37m")
  set(BOLD_RED     "${Esc}[1;31m")
  set(BOLD_GREEN   "${Esc}[1;32m")
  set(BOLD_YELLOW  "${Esc}[1;33m")
  set(BOLD_BLUE    "${Esc}[1;34m")
  set(BOLD_MAGENTA "${Esc}[1;35m")
  set(BOLD_CYAN    "${Esc}[1;36m")
  set(BOLD_WHITE   "${Esc}[1;37m")
endif()


if(CMAKE_HOST_WIN32)
    message("Host OS - Windows")
    set(COPY_CMD copy)
elseif(CMAKE_HOST_UNIX)
    message("${BOLD_BLUE}Host OS - UNIX/LINUX/MAC${COLOR_RESET}")
    set(COPY_CMD cp)
else()
    message("Host OS - Unknown")
    set(COPY_CMD cp)
endif()

if(CMAKE_HOST_WIN32)
    set(MOVE_CMD move)
elseif(CMAKE_HOST_UNIX)
    set(MOVE_CMD mv)
else()
    set(MOVE_CMD mv)
endif()

if(CMAKE_HOST_WIN32)
    set(DEL_CMD delete)
elseif(CMAKE_HOST_UNIX)
    set(DEL_CMD "rm -rf")
else()
    set(DEL_CMD "rm -rf")
endif()

if(CMAKE_HOST_WIN32)
    set(MAKE_DIR_CMD mkdir)
elseif(CMAKE_HOST_UNIX)
    set(MAKE_DIR_CMD mkdir -p)
else()
    set(MAKE_DIR_CMD mkdir)
endif()
